[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@forge-std/=lib/forge-std/src/',
    '@foundry-huff/=lib/foundry-huff/src',
    # https://www.npmjs.com/package/@openzeppelin/contracts?activeTab=versions
    '@openzeppelin-05/=lib/openzeppelin-contracts-05/contracts', # v2.5.1
    '@openzeppelin-06/=lib/openzeppelin-contracts-06/contracts', # v3.4.2
    '@openzeppelin-08/=lib/openzeppelin-contracts-08/contracts', # v5.0.2
]
ffi = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config