name: exploit

on:
  push:
    paths:
      # Github workflow
      - '.github/workflows/exploit.yml'
      # Libraries and configuration files
      - 'lib/**/*'
      - '.gitmodules'
      - 'foundry.toml'
      # Contracts and tests
      - 'src/**/*.sol'
      - 'test/**/*.t.sol'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FOUNDRY_PROFILE: ci

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install huff
        uses: huff-language/huff-toolchain@v3
        with:
          version: nightly

      - name: Run forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run forge tests (exploits)
        run: |
          forge test --ffi -vvv
        id: test
