name: lint

on:
  push:
    paths:
      # Github workflow
      - '.github/workflows/lint.yml'
      # Contracts and tests
      - 'src/**/*.sol'
      - 'test/**/*.t.sol'
      # Documentation
      - README.md

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm ci
        id: install

      - name: Run lint on Solidity code
        run: npx prettier --check 'src/**/*.sol' 'test/**/*.sol'
        id: solidity-lint

      - name: Run lint on README.md
        run: npx markdown-table-formatter --check README.md
        id: readme-lint
